import { SupportedLanguage, UserRole } from "@quickbite/types";

export interface FaqIntent {
  id: string;
  /** Lowercase English/Hinglish keywords matched against the raw user message.
   *  Real intent detection (any script, any phrasing) needs an LLM — this is
   *  the best-effort offline fallback used when no AI provider is configured. */
  keywords: string[];
  route: string;
  actionLabel: Record<SupportedLanguage, string>;
  answer: Record<SupportedLanguage, string>;
}

type L = Record<SupportedLanguage, string>;

const CUSTOMER_FAQ: FaqIntent[] = [
  {
    id: "place_order",
    keywords: ["place order", "how to order", "order food", "new order", "order kaise"],
    route: "/customer",
    actionLabel: {
      en: "Browse Restaurants", hi: "रेस्टोरेंट देखें", hinglish: "Restaurants Dekho",
      kn: "ರೆಸ್ಟೋರೆಂಟ್‌ಗಳನ್ನು ನೋಡಿ", ta: "உணவகங்களைப் பார்க்க", te: "రెస్టారెంట్లు చూడండి",
      mr: "रेस्टॉरंट पहा", bn: "রেস্তোরাঁ দেখুন", gu: "રેસ્ટોરન્ટ જુઓ", ml: "റെസ്റ്റോറന്റുകൾ കാണുക",
      pa: "ਰੈਸਟੋਰੈਂਟ ਵੇਖੋ", ur: "ریسٹورنٹ دیکھیں",
    },
    answer: {
      en: "Browse restaurants, tap a dish to add it to your cart, then checkout to place your order.",
      hi: "रेस्टोरेंट देखें, कोई डिश कार्ट में डालें, फिर चेकआउट करके ऑर्डर करें।",
      hinglish: "Restaurants browse karo, dish cart mein add karo, phir checkout karke order place karo.",
      kn: "ರೆಸ್ಟೋರೆಂಟ್ ನೋಡಿ, ಡಿಶ್ ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ, ನಂತರ ಚೆಕ್‌ಔಟ್ ಮಾಡಿ ಆರ್ಡರ್ ಮಾಡಿ.",
      ta: "உணவகங்களைப் பார்க்கவும், உணவைக் கார்ட்டில் சேர்க்கவும், பின் செக்அவுட் செய்து ஆர்டர் செய்யவும்.",
      te: "రెస్టారెంట్లు చూసి, డిష్‌ను కార్ట్‌కు జోడించి, చెక్అవుట్ చేసి ఆర్డర్ చేయండి.",
      mr: "रेस्टॉरंट पाहा, डिश कार्टमध्ये टाका, मग चेकआउट करून ऑर्डर करा.",
      bn: "রেস্তোরাঁ দেখুন, ডিশ কার্টে যোগ করুন, তারপর চেকআউট করে অর্ডার করুন।",
      gu: "રેસ્ટોરન્ટ જુઓ, ડિશ કાર્ટમાં ઉમેરો, પછી ચેકઆઉટ કરી ઓર્ડર કરો.",
      ml: "റെസ്റ്റോറന്റുകൾ കാണുക, വിഭവം കാർട്ടിൽ ചേർക്കുക, പിന്നെ ചെക്ക്ഔട്ട് ചെയ്ത് ഓർഡർ ചെയ്യുക.",
      pa: "ਰੈਸਟੋਰੈਂਟ ਵੇਖੋ, ਡਿਸ਼ ਕਾਰਟ ਵਿੱਚ ਪਾਓ, ਫਿਰ ਚੈੱਕਆਉਟ ਕਰਕੇ ਆਰਡਰ ਕਰੋ।",
      ur: "ریسٹورنٹ دیکھیں، ڈش کارٹ میں شامل کریں، پھر چیک آؤٹ کر کے آرڈر کریں۔",
    },
  },
  {
    id: "track_order",
    keywords: ["where is my order", "track order", "order status", "order kahan"],
    route: "/customer/orders",
    actionLabel: {
      en: "Track Order", hi: "ऑर्डर ट्रैक करें", hinglish: "Order Track Karo",
      kn: "ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", ta: "ஆர்டரைக் கண்காணிக்கவும்", te: "ఆర్డర్‌ను ట్రాక్ చేయండి",
      mr: "ऑर्डर ट्रॅक करा", bn: "অর্ডার ট্র্যাক করুন", gu: "ઓર્ડર ટ્રેક કરો", ml: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
      pa: "ਆਰਡਰ ਟ੍ਰੈਕ ਕਰੋ", ur: "آرڈر ٹریک کریں",
    },
    answer: {
      en: "Open Orders to see live status and tracking for every order you've placed.",
      hi: "अपने हर ऑर्डर की लाइव स्थिति देखने के लिए Orders खोलें।",
      hinglish: "Apna live order status dekhne ke liye Orders section kholo.",
      kn: "ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳ ಲೈವ್ ಸ್ಥಿತಿ ನೋಡಲು Orders ತೆರೆಯಿರಿ.",
      ta: "உங்கள் ஆர்டர்களின் நேரலை நிலையைப் பார்க்க Orders-ஐத் திறக்கவும்.",
      te: "మీ ఆర్డర్ల లైవ్ స్థితిని చూడటానికి Orders తెరవండి.",
      mr: "तुमच्या ऑर्डरची लाइव्ह स्थिती पाहण्यासाठी Orders उघडा.",
      bn: "আপনার অর্ডারের লাইভ স্ট্যাটাস দেখতে Orders খুলুন।",
      gu: "તમારા ઓર્ડરની લાઈવ સ્થિતિ જોવા Orders ખોલો.",
      ml: "നിങ്ങളുടെ ഓർഡറുകളുടെ ലൈവ് സ്റ്റാറ്റസ് കാണാൻ Orders തുറക്കുക.",
      pa: "ਆਪਣੇ ਆਰਡਰ ਦੀ ਲਾਈਵ ਸਥਿਤੀ ਵੇਖਣ ਲਈ Orders ਖੋਲ੍ਹੋ।",
      ur: "اپنے آرڈر کی لائیو صورتحال دیکھنے کے لیے Orders کھولیں۔",
    },
  },
  {
    id: "add_address",
    keywords: ["add address", "new address", "delivery address", "address kaise"],
    route: "/customer/addresses",
    actionLabel: {
      en: "Add Address", hi: "पता जोड़ें", hinglish: "Address Add Karo",
      kn: "ವಿಳಾಸ ಸೇರಿಸಿ", ta: "முகவரி சேர்க்க", te: "చిరునామా జోడించండి",
      mr: "पत्ता जोडा", bn: "ঠিকানা যোগ করুন", gu: "સરનામું ઉમેરો", ml: "വിലാസം ചേർക്കുക",
      pa: "ਪਤਾ ਸ਼ਾਮਲ ਕਰੋ", ur: "پتہ شامل کریں",
    },
    answer: {
      en: "Go to Addresses, tap + New, and save your delivery address there.",
      hi: "Addresses में जाएं, + New दबाएं, और अपना पता सेव करें।",
      hinglish: "Addresses mein jao, + New dabao, aur apna address save karo.",
      kn: "Addresses ಗೆ ಹೋಗಿ, + New ಒತ್ತಿ, ನಿಮ್ಮ ವಿಳಾಸ ಉಳಿಸಿ.",
      ta: "Addresses-க்குச் சென்று, + New அழுத்தி, உங்கள் முகவரியைச் சேமிக்கவும்.",
      te: "Addresses కి వెళ్లి, + New నొక్కి, మీ చిరునామాను సేవ్ చేయండి.",
      mr: "Addresses मध्ये जा, + New दाबा, आणि पत्ता सेव्ह करा.",
      bn: "Addresses-এ যান, + New চাপুন, এবং ঠিকানা সেভ করুন।",
      gu: "Addresses પર જાઓ, + New દબાવો, અને સરનામું સેવ કરો.",
      ml: "Addresses-ലേക്ക് പോയി, + New അമർത്തി, വിലാസം സേവ് ചെയ്യുക.",
      pa: "Addresses ਤੇ ਜਾਓ, + New ਦਬਾਓ, ਅਤੇ ਪਤਾ ਸੇਵ ਕਰੋ।",
      ur: "Addresses پر جائیں، + New دبائیں، اور اپنا پتہ محفوظ کریں۔",
    },
  },
  {
    id: "use_coupon",
    keywords: ["coupon", "promo code", "discount code", "offer code"],
    route: "/customer/checkout",
    actionLabel: {
      en: "Payment Help", hi: "भुगतान सहायता", hinglish: "Payment Help",
      kn: "ಪಾವತಿ ಸಹಾಯ", ta: "பணம் செலுத்த உதவி", te: "చెల్లింపు సహాయం",
      mr: "पेमेंट मदत", bn: "পেমেন্ট সহায়তা", gu: "પેમેન્ટ મદદ", ml: "പേയ്‌മെന്റ് സഹായം",
      pa: "ਭੁਗਤਾਨ ਮਦਦ", ur: "ادائیگی میں مدد",
    },
    answer: {
      en: "Enter your coupon code in the Coupon box at checkout and tap Apply.",
      hi: "चेकआउट पर Coupon बॉक्स में कोड डालें और Apply दबाएं।",
      hinglish: "Checkout pe Coupon box mein code daalo aur Apply dabao.",
      kn: "ಚೆಕ್‌ಔಟ್‌ನಲ್ಲಿ Coupon ಬಾಕ್ಸ್‌ನಲ್ಲಿ ಕೋಡ್ ಹಾಕಿ Apply ಒತ್ತಿ.",
      ta: "செக்அவுட்டில் Coupon பெட்டியில் குறியீட்டை உள்ளிட்டு Apply அழுத்தவும்.",
      te: "చెక్అవుట్‌లో Coupon బాక్స్‌లో కోడ్ నమోదు చేసి Apply నొక్కండి.",
      mr: "चेकआउटवर Coupon बॉक्समध्ये कोड टाका आणि Apply दाबा.",
      bn: "চেকআউটে Coupon বক্সে কোড দিন এবং Apply চাপুন।",
      gu: "ચેકઆઉટ પર Coupon બોક્સમાં કોડ નાખો અને Apply દબાવો.",
      ml: "ചെക്ക്ഔട്ടിൽ Coupon ബോക്സിൽ കോഡ് നൽകി Apply അമർത്തുക.",
      pa: "ਚੈੱਕਆਉਟ ਤੇ Coupon ਬਾਕਸ ਵਿੱਚ ਕੋਡ ਪਾਓ ਅਤੇ Apply ਦਬਾਓ।",
      ur: "چیک آؤٹ پر Coupon باکس میں کوڈ درج کریں اور Apply دبائیں۔",
    },
  },
  {
    id: "delivery_status",
    keywords: ["where is my delivery", "delivery status", "rider location", "driver location"],
    route: "/customer/orders",
    actionLabel: {
      en: "Track Order", hi: "ऑर्डर ट्रैक करें", hinglish: "Order Track Karo",
      kn: "ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", ta: "ஆர்டரைக் கண்காணிக்கவும்", te: "ఆర్డర్‌ను ట్రాక్ చేయండి",
      mr: "ऑर्डर ट्रॅक करा", bn: "অর্ডার ট্র্যাক করুন", gu: "ઓર્ડર ટ્રેક કરો", ml: "ഓർഡർ ട്രാക്ക് ചെയ്യുക",
      pa: "ਆਰਡਰ ਟ੍ਰੈਕ ਕਰੋ", ur: "آرڈر ٹریک کریں",
    },
    answer: {
      en: "Open your order's tracking page to see live delivery progress.",
      hi: "लाइव डिलीवरी प्रगति देखने के लिए अपने ऑर्डर का ट्रैकिंग पेज खोलें।",
      hinglish: "Live delivery progress dekhne ke liye order ka tracking page kholo.",
      kn: "ಲೈವ್ ಡೆಲಿವರಿ ಪ್ರಗತಿ ನೋಡಲು ನಿಮ್ಮ ಆರ್ಡರ್‌ನ ಟ್ರ್ಯಾಕಿಂಗ್ ಪುಟ ತೆರೆಯಿರಿ.",
      ta: "நேரலை டெலிவரி முன்னேற்றத்தைப் பார்க்க உங்கள் ஆர்டர் டிராக்கிங் பக்கத்தைத் திறக்கவும்.",
      te: "లైవ్ డెలివరీ పురోగతిని చూడటానికి మీ ఆర్డర్ ట్రాకింగ్ పేజీని తెరవండి.",
      mr: "लाइव्ह डिलिव्हरी प्रगती पाहण्यासाठी ऑर्डर ट्रॅकिंग पेज उघडा.",
      bn: "লাইভ ডেলিভারি অগ্রগতি দেখতে অর্ডারের ট্র্যাকিং পেজ খুলুন।",
      gu: "લાઈવ ડિલિવરી પ્રગતિ જોવા ઓર્ડરનું ટ્રેકિંગ પેજ ખોલો.",
      ml: "ലൈവ് ഡെലിവറി പുരോഗതി കാണാൻ ഓർഡർ ട്രാക്കിംഗ് പേജ് തുറക്കുക.",
      pa: "ਲਾਈਵ ਡਿਲੀਵਰੀ ਤਰੱਕੀ ਵੇਖਣ ਲਈ ਆਰਡਰ ਟ੍ਰੈਕਿੰਗ ਪੇਜ ਖੋਲ੍ਹੋ।",
      ur: "لائیو ڈिلیوری کی پیش رفت دیکھنے کے لیے آرڈر ٹریکنگ پیج کھولیں۔",
    },
  },
  {
    id: "cod_payment",
    keywords: ["cod", "cash on delivery", "pay cash"],
    route: "/customer/checkout",
    actionLabel: {
      en: "Payment Help", hi: "भुगतान सहायता", hinglish: "Payment Help",
      kn: "ಪಾವತಿ ಸಹಾಯ", ta: "பணம் செலுத்த உதவி", te: "చెల్లింపు సహాయం",
      mr: "पेमेंट मदत", bn: "পেমেন্ট সহায়তা", gu: "પેમેન્ટ મદદ", ml: "പേയ്‌മെന്റ് സഹായം",
      pa: "ਭੁਗਤਾਨ ਮਦਦ", ur: "ادائیگی میں مدد",
    },
    answer: {
      en: "Choose Cash on Delivery as your payment method at checkout.",
      hi: "चेकआउट पर भुगतान विधि के रूप में Cash on Delivery चुनें।",
      hinglish: "Checkout pe payment method mein Cash on Delivery select karo.",
      kn: "ಚೆಕ್‌ಔಟ್‌ನಲ್ಲಿ ಪಾವತಿ ವಿಧಾನವಾಗಿ Cash on Delivery ಆಯ್ಕೆಮಾಡಿ.",
      ta: "செக்அவுட்டில் பணம் செலுத்தும் முறையாக Cash on Delivery-ஐத் தேர்வு செய்யவும்.",
      te: "చెక్అవుట్‌లో చెల్లింపు విధానంగా Cash on Delivery ఎంచుకోండి.",
      mr: "चेकआउटवर पेमेंट पद्धत म्हणून Cash on Delivery निवडा.",
      bn: "চেকআউটে পেমেন্ট পদ্ধতি হিসেবে Cash on Delivery বেছে নিন।",
      gu: "ચેકઆઉટ પર પેમેન્ટ પદ્ધતિ તરીકે Cash on Delivery પસંદ કરો.",
      ml: "ചെക്ക്ഔട്ടിൽ പേയ്‌മെന്റ് രീതിയായി Cash on Delivery തിരഞ്ഞെടുക്കുക.",
      pa: "ਚੈੱਕਆਉਟ ਤੇ ਭੁਗਤਾਨ ਢੰਗ ਵਜੋਂ Cash on Delivery ਚੁਣੋ।",
      ur: "چیک آؤٹ پر ادائیگی کے طریقے کے طور پر Cash on Delivery منتخب کریں۔",
    },
  },
  {
    id: "contact_support",
    keywords: ["contact support", "customer care", "complaint", "help"],
    route: "/customer/help",
    actionLabel: {
      en: "Contact Support", hi: "सहायता से संपर्क करें", hinglish: "Support Contact Karo",
      kn: "ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ", ta: "ஆதரவைத் தொடர்பு கொள்ள", te: "సపోర్ట్‌ను సంప్రదించండి",
      mr: "सपोर्टशी संपर्क करा", bn: "সাপোর্টে যোগাযোগ করুন", gu: "સપોર્ટનો સંપર્ક કરો", ml: "സപ്പോർട്ടിനെ ബന്ധപ്പെടുക",
      pa: "ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ", ur: "سپورٹ سے رابطہ کریں",
    },
    answer: {
      en: "Visit the Help page to browse FAQs or raise a support ticket.",
      hi: "FAQ देखने या टिकट बनाने के लिए Help पेज पर जाएं।",
      hinglish: "FAQs dekhne ya ticket banane ke liye Help page pe jao.",
      kn: "FAQ ನೋಡಲು ಅಥವಾ ಟಿಕೆಟ್ ಸಲ್ಲಿಸಲು Help ಪುಟಕ್ಕೆ ಹೋಗಿ.",
      ta: "FAQகளைப் பார்க்க அல்லது டிக்கெட் இட Help பக்கத்திற்குச் செல்லவும்.",
      te: "FAQలు చూడటానికి లేదా టికెట్ పెట్టడానికి Help పేజీకి వెళ్లండి.",
      mr: "FAQ पाहण्यासाठी किंवा तिकीट काढण्यासाठी Help पेजवर जा.",
      bn: "FAQ দেখতে বা টিকিট তুলতে Help পেজে যান।",
      gu: "FAQ જોવા અથવા ટિકિટ કરવા Help પેજ પર જાઓ.",
      ml: "FAQ കാണാനോ ടിക്കറ്റ് ഇടാനോ Help പേജിലേക്ക് പോകുക.",
      pa: "FAQ ਵੇਖਣ ਜਾਂ ਟਿਕਟ ਬਣਾਉਣ ਲਈ Help ਪੇਜ ਤੇ ਜਾਓ।",
      ur: "FAQs دیکھنے یا ٹکٹ بنانے کے لیے Help پیج پر جائیں۔",
    },
  },
];

const RESTAURANT_FAQ: FaqIntent[] = [
  {
    id: "accept_order",
    keywords: ["accept order", "new order", "incoming order"],
    route: "/restaurant/kitchen",
    actionLabel: {
      en: "Kitchen", hi: "किचन", hinglish: "Kitchen",
      kn: "ಅಡುಗೆಮನೆ", ta: "சமையலறை", te: "కిచెన్",
      mr: "किचन", bn: "কিচেন", gu: "કિચન", ml: "അടുക്കള",
      pa: "ਰਸੋਈ", ur: "کچن",
    },
    answer: {
      en: "Open Kitchen and tap Accept on an incoming order to start preparing it.",
      hi: "Kitchen खोलें और नए ऑर्डर पर Accept दबाकर तैयारी शुरू करें।",
      hinglish: "Kitchen kholo aur naye order pe Accept dabao, taiyari shuru karo.",
      kn: "Kitchen ತೆರೆದು ಹೊಸ ಆರ್ಡರ್‌ನಲ್ಲಿ Accept ಒತ್ತಿ ತಯಾರಿ ಆರಂಭಿಸಿ.",
      ta: "Kitchen-ஐத் திறந்து புதிய ஆர்டரில் Accept அழுத்தி தயாரிப்பைத் தொடங்கவும்.",
      te: "Kitchen తెరిచి కొత్త ఆర్డర్‌పై Accept నొక్కి తయారీ మొదలుపెట్టండి.",
      mr: "Kitchen उघडा आणि नवीन ऑर्डरवर Accept दाबून तयारी सुरू करा.",
      bn: "Kitchen খুলে নতুন অর্ডারে Accept চাপুন এবং তৈরি শুরু করুন।",
      gu: "Kitchen ખોલો અને નવા ઓર્ડર પર Accept દબાવી તૈયારી શરૂ કરો.",
      ml: "Kitchen തുറന്ന് പുതിയ ഓർഡറിൽ Accept അമർത്തി തയ്യാറാക്കൽ തുടങ്ങുക.",
      pa: "Kitchen ਖੋਲ੍ਹੋ ਅਤੇ ਨਵੇਂ ਆਰਡਰ ਤੇ Accept ਦਬਾ ਕੇ ਤਿਆਰੀ ਸ਼ੁਰੂ ਕਰੋ।",
      ur: "Kitchen کھولیں اور نئے آرڈر پر Accept دبا کر تیاری شروع کریں۔",
    },
  },
  {
    id: "move_preparing",
    keywords: ["move to preparing", "start preparing", "preparing"],
    route: "/restaurant/kitchen",
    actionLabel: {
      en: "Kitchen", hi: "किचन", hinglish: "Kitchen",
      kn: "ಅಡುಗೆಮನೆ", ta: "சமையலறை", te: "కిచెన్",
      mr: "किचन", bn: "কিচেন", gu: "કિચન", ml: "അടുക്കള",
      pa: "ਰਸੋਈ", ur: "کچن",
    },
    answer: {
      en: "In Kitchen, tap Start Preparing on an accepted order to move it forward.",
      hi: "Kitchen में, स्वीकृत ऑर्डर पर Start Preparing दबाएं।",
      hinglish: "Kitchen mein, accept kiye order pe Start Preparing dabao.",
      kn: "Kitchen ನಲ್ಲಿ, ಸ್ವೀಕರಿಸಿದ ಆರ್ಡರ್‌ನಲ್ಲಿ Start Preparing ಒತ್ತಿ.",
      ta: "Kitchen-இல், ஏற்றுக்கொண்ட ஆர்டரில் Start Preparing அழுத்தவும்.",
      te: "Kitchen లో, అంగీకరించిన ఆర్డర్‌పై Start Preparing నొక్కండి.",
      mr: "Kitchen मध्ये, स्वीकारलेल्या ऑर्डरवर Start Preparing दाबा.",
      bn: "Kitchen-এ, গৃহীত অর্ডারে Start Preparing চাপুন।",
      gu: "Kitchen માં, સ્વીકારેલા ઓર્ડર પર Start Preparing દબાવો.",
      ml: "Kitchen-ൽ, സ്വീകരിച്ച ഓർഡറിൽ Start Preparing അമർത്തുക.",
      pa: "Kitchen ਵਿੱਚ, ਸਵੀਕਾਰ ਕੀਤੇ ਆਰਡਰ ਤੇ Start Preparing ਦਬਾਓ।",
      ur: "Kitchen میں، قبول شدہ آرڈر پر Start Preparing دبائیں۔",
    },
  },
  {
    id: "pickup_otp",
    keywords: ["pickup otp", "generate otp", "otp generate"],
    route: "/restaurant/kitchen",
    actionLabel: {
      en: "Pickup OTP", hi: "पिकअप OTP", hinglish: "Pickup OTP",
      kn: "ಪಿಕಪ್ OTP", ta: "பிக்அப் OTP", te: "పికప్ OTP",
      mr: "पिकअप OTP", bn: "পিকআপ OTP", gu: "પિકઅપ OTP", ml: "പിക്കപ്പ് OTP",
      pa: "ਪਿਕਅੱਪ OTP", ur: "پک اپ OTP",
    },
    answer: {
      en: "In Kitchen, tap Generate Pickup OTP once an order is Ready for Pickup.",
      hi: "ऑर्डर Ready for Pickup होने पर Kitchen में Generate Pickup OTP दबाएं।",
      hinglish: "Order Ready for Pickup hone par Kitchen mein Generate Pickup OTP dabao.",
      kn: "ಆರ್ಡರ್ Ready for Pickup ಆದಾಗ Kitchen ನಲ್ಲಿ Generate Pickup OTP ಒತ್ತಿ.",
      ta: "ஆர்டர் Ready for Pickup ஆனதும் Kitchen-இல் Generate Pickup OTP அழுத்தவும்.",
      te: "ఆర్డర్ Ready for Pickup అయ్యాక Kitchen లో Generate Pickup OTP నొక్కండి.",
      mr: "ऑर्डर Ready for Pickup झाल्यावर Kitchen मध्ये Generate Pickup OTP दाबा.",
      bn: "অর্ডার Ready for Pickup হলে Kitchen-এ Generate Pickup OTP চাপুন।",
      gu: "ઓર્ડર Ready for Pickup થાય ત્યારે Kitchen માં Generate Pickup OTP દબાવો.",
      ml: "ഓർഡർ Ready for Pickup ആകുമ്പോൾ Kitchen-ൽ Generate Pickup OTP അമർത്തുക.",
      pa: "ਆਰਡਰ Ready for Pickup ਹੋਣ ਤੇ Kitchen ਵਿੱਚ Generate Pickup OTP ਦਬਾਓ।",
      ur: "آرڈر Ready for Pickup ہونے پر Kitchen میں Generate Pickup OTP دبائیں۔",
    },
  },
  {
    id: "todays_orders",
    keywords: ["today's orders", "today orders", "see orders", "todays orders"],
    route: "/restaurant",
    actionLabel: {
      en: "Orders", hi: "ऑर्डर", hinglish: "Orders",
      kn: "ಆರ್ಡರ್‌ಗಳು", ta: "ஆர்டர்கள்", te: "ఆర్డర్లు",
      mr: "ऑर्डर्स", bn: "অর্ডার", gu: "ઓર્ડર", ml: "ഓർഡറുകൾ",
      pa: "ਆਰਡਰ", ur: "آرڈرز",
    },
    answer: {
      en: "Your Dashboard shows today's orders, active orders and revenue at a glance.",
      hi: "आपका Dashboard आज के ऑर्डर, सक्रिय ऑर्डर और आय एक नज़र में दिखाता है।",
      hinglish: "Dashboard pe aaj ke orders, active orders aur revenue ek jagah dikhta hai.",
      kn: "ನಿಮ್ಮ Dashboard ಇಂದಿನ ಆರ್ಡರ್, ಸಕ್ರಿಯ ಆರ್ಡರ್ ಮತ್ತು ಆದಾಯ ತೋರಿಸುತ್ತದೆ.",
      ta: "உங்கள் Dashboard இன்றைய ஆர்டர்கள், செயலில் உள்ள ஆர்டர்கள் மற்றும் வருவாயைக் காட்டுகிறது.",
      te: "మీ Dashboard నేటి ఆర్డర్లు, యాక్టివ్ ఆర్డర్లు మరియు ఆదాయాన్ని చూపిస్తుంది.",
      mr: "तुमचा Dashboard आजचे ऑर्डर्स, सक्रिय ऑर्डर्स आणि महसूल दाखवतो.",
      bn: "আপনার Dashboard আজকের অর্ডার, সক্রিয় অর্ডার এবং আয় দেখায়।",
      gu: "તમારું Dashboard આજના ઓર્ડર, સક્રિય ઓર્ડર અને આવક બતાવે છે.",
      ml: "നിങ്ങളുടെ Dashboard ഇന്നത്തെ ഓർഡറുകൾ, ആക്ടീവ് ഓർഡറുകൾ, വരുമാനം കാണിക്കുന്നു.",
      pa: "ਤੁਹਾਡਾ Dashboard ਅੱਜ ਦੇ ਆਰਡਰ, ਸਰਗਰਮ ਆਰਡਰ ਅਤੇ ਆਮਦਨ ਵਿਖਾਉਂਦਾ ਹੈ।",
      ur: "آپ کا Dashboard آج کے آرڈرز، فعال آرڈرز اور آمدنی دکھاتا ہے۔",
    },
  },
  {
    id: "update_menu",
    keywords: ["update menu", "edit menu", "add dish", "menu change"],
    route: "/restaurant/menu",
    actionLabel: {
      en: "Menu", hi: "मेन्यू", hinglish: "Menu",
      kn: "ಮೆನು", ta: "மெனு", te: "మెనూ",
      mr: "मेनू", bn: "মেনু", gu: "મેનૂ", ml: "മെനു",
      pa: "ਮੀਨੂ", ur: "مینو",
    },
    answer: {
      en: "Open Menu to add categories, add dishes, or toggle stock availability.",
      hi: "Menu खोलकर कैटेगरी, डिश जोड़ें या स्टॉक बदलें।",
      hinglish: "Menu kholo categories add karo, dish add karo, ya stock toggle karo.",
      kn: "Menu ತೆರೆದು ವಿಭಾಗ, ಖಾದ್ಯ ಸೇರಿಸಿ ಅಥವಾ ಸ್ಟಾಕ್ ಬದಲಿಸಿ.",
      ta: "Menu-ஐத் திறந்து வகைகள், உணவுகள் சேர்க்கவும் அல்லது ஸ்டாக்கை மாற்றவும்.",
      te: "Menu తెరిచి కేటగిరీలు, డిష్‌లు జోడించండి లేదా స్టాక్ మార్చండి.",
      mr: "Menu उघडून श्रेणी, डिश जोडा किंवा स्टॉक बदला.",
      bn: "Menu খুলে ক্যাটাগরি, ডিশ যোগ করুন বা স্টক পরিবর্তন করুন।",
      gu: "Menu ખોલી કેટેગરી, ડિશ ઉમેરો અથવા સ્ટોક બદલો.",
      ml: "Menu തുറന്ന് വിഭാഗങ്ങൾ, വിഭവങ്ങൾ ചേർക്കുക അല്ലെങ്കിൽ സ്റ്റോക്ക് മാറ്റുക.",
      pa: "Menu ਖੋਲ੍ਹ ਕੇ ਸ਼੍ਰੇਣੀਆਂ, ਪਕਵਾਨ ਸ਼ਾਮਲ ਕਰੋ ਜਾਂ ਸਟਾਕ ਬਦਲੋ।",
      ur: "Menu کھول کر کیٹگری، ڈش شامل کریں یا اسٹاک تبدیل کریں۔",
    },
  },
];

const DRIVER_FAQ: FaqIntent[] = [
  {
    id: "accept_delivery",
    keywords: ["accept delivery", "new delivery", "incoming offer"],
    route: "/delivery",
    actionLabel: {
      en: "Dashboard", hi: "डैशबोर्ड", hinglish: "Dashboard",
      kn: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", ta: "டாஷ்போர்டு", te: "డాష్‌బోర్డ్",
      mr: "डॅशबोर्ड", bn: "ড্যাশবোর্ড", gu: "ડેશબોર્ડ", ml: "ഡാഷ്ബോർഡ്",
      pa: "ਡੈਸ਼ਬੋਰਡ", ur: "ڈیش بورڈ",
    },
    answer: {
      en: "When an offer pops up, tap Accept before the timer runs out.",
      hi: "जब कोई ऑफर आए, टाइमर खत्म होने से पहले Accept दबाएं।",
      hinglish: "Jab offer aaye, timer khatam hone se pehle Accept dabao.",
      kn: "ಆಫರ್ ಬಂದಾಗ, ಟೈಮರ್ ಮುಗಿಯುವ ಮೊದಲು Accept ಒತ್ತಿ.",
      ta: "ஆஃபர் வரும்போது, டைமர் முடிவதற்குள் Accept அழுத்தவும்.",
      te: "ఆఫర్ వచ్చినప్పుడు, టైమర్ అయిపోకముందే Accept నొక్కండి.",
      mr: "ऑफर आल्यावर, टायमर संपण्याआधी Accept दाबा.",
      bn: "অফার এলে, টাইমার শেষ হওয়ার আগে Accept চাপুন।",
      gu: "ઓફર આવે ત્યારે, ટાઈમર પૂરો થાય પહેલાં Accept દબાવો.",
      ml: "ഓഫർ വരുമ്പോൾ, ടൈമർ തീരും മുൻപ് Accept അമർത്തുക.",
      pa: "ਜਦੋਂ ਆਫਰ ਆਵੇ, ਟਾਈਮਰ ਖਤਮ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ Accept ਦਬਾਓ।",
      ur: "جب آفر آئے، ٹائمر ختم ہونے سے پہلے Accept دبائیں۔",
    },
  },
  {
    id: "pickup_otp_location",
    keywords: ["where is the pickup otp", "pickup otp"],
    route: "/delivery/active",
    actionLabel: {
      en: "Active Delivery", hi: "सक्रिय डिलीवरी", hinglish: "Active Delivery",
      kn: "ಸಕ್ರಿಯ ಡೆಲಿವರಿ", ta: "செயலில் உள்ள டெலிவரி", te: "యాక్టివ్ డెలివరీ",
      mr: "सक्रिय डिलिव्हरी", bn: "সক্রিয় ডেলিভারি", gu: "સક્રિય ડિલિવરી", ml: "ആക്ടീവ് ഡെലിവറി",
      pa: "ਸਰਗਰਮ ਡਿਲੀਵਰੀ", ur: "فعال ڈिلیوری",
    },
    answer: {
      en: "The restaurant shows you the Pickup OTP — enter it on your Active Delivery screen.",
      hi: "रेस्टोरेंट आपको Pickup OTP दिखाता है — इसे Active Delivery स्क्रीन पर डालें।",
      hinglish: "Restaurant tumhe Pickup OTP dikhata hai — Active Delivery screen pe daalo.",
      kn: "ರೆಸ್ಟೋರೆಂಟ್ ನಿಮಗೆ Pickup OTP ತೋರಿಸುತ್ತದೆ — Active Delivery ಪರದೆಯಲ್ಲಿ ಹಾಕಿ.",
      ta: "உணவகம் Pickup OTP-ஐக் காட்டும் — Active Delivery திரையில் உள்ளிடவும்.",
      te: "రెస్టారెంట్ మీకు Pickup OTP చూపిస్తుంది — Active Delivery స్క్రీన్‌లో నమోదు చేయండి.",
      mr: "रेस्टॉरंट तुम्हाला Pickup OTP दाखवते — Active Delivery स्क्रीनवर टाका.",
      bn: "রেস্তোরাঁ আপনাকে Pickup OTP দেখায় — Active Delivery স্ক্রিনে দিন।",
      gu: "રેસ્ટોરન્ટ તમને Pickup OTP બતાવે છે — Active Delivery સ્ક્રીન પર નાખો.",
      ml: "റെസ്റ്റോറന്റ് നിങ്ങൾക്ക് Pickup OTP കാണിക്കും — Active Delivery സ്ക്രീനിൽ നൽകുക.",
      pa: "ਰੈਸਟੋਰੈਂਟ ਤੁਹਾਨੂੰ Pickup OTP ਵਿਖਾਉਂਦਾ ਹੈ — Active Delivery ਸਕਰੀਨ ਤੇ ਪਾਓ।",
      ur: "ریسٹورنٹ آپ کو Pickup OTP دکھاتا ہے — اسے Active Delivery اسکرین پر درج کریں۔",
    },
  },
  {
    id: "mark_pickup",
    keywords: ["mark pickup", "picked up", "how to pick up"],
    route: "/delivery/active",
    actionLabel: {
      en: "Active Delivery", hi: "सक्रिय डिलीवरी", hinglish: "Active Delivery",
      kn: "ಸಕ್ರಿಯ ಡೆಲಿವರಿ", ta: "செயலில் உள்ள டெலிவரி", te: "యాక్టివ్ డెలివరీ",
      mr: "सक्रिय डिलिव्हरी", bn: "সক্রিয় ডেলিভারি", gu: "સક્રિય ડિલિવરી", ml: "ആക്ടീവ് ഡെലിവറി",
      pa: "ਸਰਗਰਮ ਡਿਲੀਵਰੀ", ur: "فعال ڈिلیوری",
    },
    answer: {
      en: "On Active Delivery, enter the Pickup OTP and tap Verify to mark it picked up.",
      hi: "Active Delivery पर Pickup OTP डालें और Verify दबाकर पिकअप मार्क करें।",
      hinglish: "Active Delivery pe Pickup OTP daalo aur Verify dabake pickup mark karo.",
      kn: "Active Delivery ನಲ್ಲಿ Pickup OTP ಹಾಕಿ Verify ಒತ್ತಿ ಪಿಕಪ್ ಗುರುತಿಸಿ.",
      ta: "Active Delivery-இல் Pickup OTP-ஐ உள்ளிட்டு Verify அழுத்தி பிக்அப் குறிக்கவும்.",
      te: "Active Delivery లో Pickup OTP నమోదు చేసి Verify నొక్కి పికప్ మార్క్ చేయండి.",
      mr: "Active Delivery वर Pickup OTP टाका आणि Verify दाबून पिकअप मार्क करा.",
      bn: "Active Delivery-তে Pickup OTP দিন এবং Verify চেপে পিকআপ মার্ক করুন।",
      gu: "Active Delivery પર Pickup OTP નાખો અને Verify દબાવી પિકઅપ માર્ક કરો.",
      ml: "Active Delivery-ൽ Pickup OTP നൽകി Verify അമർത്തി പിക്കപ്പ് മാർക്ക് ചെയ്യുക.",
      pa: "Active Delivery ਤੇ Pickup OTP ਪਾਓ ਅਤੇ Verify ਦਬਾ ਕੇ ਪਿਕਅੱਪ ਮਾਰਕ ਕਰੋ।",
      ur: "Active Delivery پر Pickup OTP درج کریں اور Verify دبا کر پک اپ مارک کریں۔",
    },
  },
  {
    id: "customer_location",
    keywords: ["customer location", "where is customer", "customer address"],
    route: "/delivery/active",
    actionLabel: {
      en: "Navigation", hi: "नेविगेशन", hinglish: "Navigation",
      kn: "ನ್ಯಾವಿಗೇಷನ್", ta: "வழிசெலுத்தல்", te: "నావిగేషన్",
      mr: "नेव्हिगेशन", bn: "নেভিগেশন", gu: "નેવિગેશન", ml: "നാവിഗേഷൻ",
      pa: "ਨੇਵੀਗੇਸ਼ਨ", ur: "نیویگیشن",
    },
    answer: {
      en: "The customer's address and a Navigate button are on your Active Delivery screen.",
      hi: "ग्राहक का पता और Navigate बटन आपकी Active Delivery स्क्रीन पर है।",
      hinglish: "Customer ka address aur Navigate button Active Delivery screen pe hai.",
      kn: "ಗ್ರಾಹಕರ ವಿಳಾಸ ಮತ್ತು Navigate ಬಟನ್ Active Delivery ಪರದೆಯಲ್ಲಿದೆ.",
      ta: "வாடிக்கையாளர் முகவரி மற்றும் Navigate பொத்தான் Active Delivery திரையில் உள்ளது.",
      te: "కస్టమర్ చిరునామా మరియు Navigate బటన్ మీ Active Delivery స్క్రీన్‌లో ఉంది.",
      mr: "ग्राहकाचा पत्ता आणि Navigate बटण Active Delivery स्क्रीनवर आहे.",
      bn: "গ্রাহকের ঠিকানা এবং Navigate বাটন Active Delivery স্ক্রিনে আছে।",
      gu: "ગ્રાહકનું સરનામું અને Navigate બટન Active Delivery સ્ક્રીન પર છે.",
      ml: "ഉപഭോക്താവിന്റെ വിലാസവും Navigate ബട്ടണും Active Delivery സ്ക്രീനിലുണ്ട്.",
      pa: "ਗਾਹਕ ਦਾ ਪਤਾ ਅਤੇ Navigate ਬਟਨ Active Delivery ਸਕਰੀਨ ਤੇ ਹੈ।",
      ur: "کسٹمر کا پتہ اور Navigate بٹن Active Delivery اسکرین پر ہے۔",
    },
  },
  {
    id: "complete_delivery",
    keywords: ["complete delivery", "finish delivery", "drop otp"],
    route: "/delivery/active",
    actionLabel: {
      en: "Active Delivery", hi: "सक्रिय डिलीवरी", hinglish: "Active Delivery",
      kn: "ಸಕ್ರಿಯ ಡೆಲಿವರಿ", ta: "செயலில் உள்ள டெலிவரி", te: "యాక్టివ్ డెలివరీ",
      mr: "सक्रिय डिलिव्हरी", bn: "সক্রিয় ডেলিভারি", gu: "સક્રિય ડિલિવરી", ml: "ആക്ടീവ് ഡെലിവறി",
      pa: "ਸਰਗਰਮ ਡਿਲੀਵਰੀ", ur: "فعال ڈिلیوری",
    },
    answer: {
      en: "Enter the Drop OTP from the customer on Active Delivery to complete it.",
      hi: "पूरा करने के लिए ग्राहक से Drop OTP लेकर Active Delivery में डालें।",
      hinglish: "Complete karne ke liye customer se Drop OTP lekar Active Delivery mein daalo.",
      kn: "ಪೂರ್ಣಗೊಳಿಸಲು ಗ್ರಾಹಕರಿಂದ Drop OTP ಪಡೆದು Active Delivery ನಲ್ಲಿ ಹಾಕಿ.",
      ta: "முடிக்க வாடிக்கையாளரிடமிருந்து Drop OTP-ஐப் பெற்று Active Delivery-இல் உள்ளிடவும்.",
      te: "పూర్తి చేయడానికి కస్టమర్ నుండి Drop OTP తీసుకుని Active Delivery లో నమోదు చేయండి.",
      mr: "पूर्ण करण्यासाठी ग्राहकाकडून Drop OTP घेऊन Active Delivery मध्ये टाका.",
      bn: "সম্পূর্ণ করতে গ্রাহকের কাছ থেকে Drop OTP নিয়ে Active Delivery-তে দিন।",
      gu: "પૂર્ણ કરવા ગ્રાહક પાસેથી Drop OTP લઈ Active Delivery માં નાખો.",
      ml: "പൂർത്തിയാക്കാൻ ഉപഭോക്താവിൽ നിന്ന് Drop OTP വാങ്ങി Active Delivery-ൽ നൽകുക.",
      pa: "ਪੂਰਾ ਕਰਨ ਲਈ ਗਾਹਕ ਤੋਂ Drop OTP ਲੈ ਕੇ Active Delivery ਵਿੱਚ ਪਾਓ।",
      ur: "مکمل کرنے کے لیے کسٹمر سے Drop OTP لے کر Active Delivery میں درج کریں۔",
    },
  },
  {
    id: "view_trips",
    keywords: ["my trips", "trip history", "past deliveries"],
    route: "/delivery/history",
    actionLabel: {
      en: "Trips", hi: "ट्रिप्स", hinglish: "Trips",
      kn: "ಟ್ರಿಪ್‌ಗಳು", ta: "பயணங்கள்", te: "ట్రిప్‌లు",
      mr: "ट्रिप्स", bn: "ট্রিপ", gu: "ટ્રિપ્સ", ml: "ട്രിപ്പുകൾ",
      pa: "ਟ੍ਰਿਪਸ", ur: "ٹرپس",
    },
    answer: {
      en: "Open Trips to see your full delivery history.",
      hi: "अपनी पूरी डिलीवरी हिस्ट्री देखने के लिए Trips खोलें।",
      hinglish: "Apni poori delivery history dekhne ke liye Trips kholo.",
      kn: "ನಿಮ್ಮ ಪೂರ್ಣ ಡೆಲಿವರಿ ಇತಿಹಾಸ ನೋಡಲು Trips ತೆರೆಯಿರಿ.",
      ta: "உங்கள் முழு டெலிவரி வரலாற்றைப் பார்க்க Trips-ஐத் திறக்கவும்.",
      te: "మీ పూర్తి డెలివరీ చరిత్రను చూడటానికి Trips తెరవండి.",
      mr: "तुमचा संपूर्ण डिलिव्हरी इतिहास पाहण्यासाठी Trips उघडा.",
      bn: "আপনার সম্পূর্ণ ডেলিভারি ইতিহাস দেখতে Trips খুলুন।",
      gu: "તમારો સંપૂર્ણ ડિલિવરી ઇતિહાસ જોવા Trips ખોલો.",
      ml: "നിങ്ങളുടെ മുഴുവൻ ഡെലിവറി ചരിത്രം കാണാൻ Trips തുറക്കുക.",
      pa: "ਆਪਣਾ ਪੂਰਾ ਡਿਲੀਵਰੀ ਇਤਿਹਾਸ ਵੇਖਣ ਲਈ Trips ਖੋਲ੍ਹੋ।",
      ur: "اپنی مکمل ڈिلیوری ہسٹری دیکھنے کے لیے Trips کھولیں۔",
    },
  },
  {
    id: "view_wallet",
    keywords: ["wallet", "earnings", "my payouts", "payout"],
    route: "/delivery/payouts",
    actionLabel: {
      en: "Wallet", hi: "वॉलेट", hinglish: "Wallet",
      kn: "ವಾಲೆಟ್", ta: "வாலட்", te: "వాలెట్",
      mr: "वॉलेट", bn: "ওয়ালেট", gu: "વોલેટ", ml: "വാലറ്റ്",
      pa: "ਵਾਲਿਟ", ur: "والٹ",
    },
    answer: {
      en: "Open Wallet to see your earnings and payout summary.",
      hi: "अपनी कमाई और भुगतान देखने के लिए Wallet खोलें।",
      hinglish: "Apni earnings aur payout dekhne ke liye Wallet kholo.",
      kn: "ನಿಮ್ಮ ಗಳಿಕೆ ಮತ್ತು ಪಾವತಿ ನೋಡಲು Wallet ತೆರೆಯಿರಿ.",
      ta: "உங்கள் வருமானம் மற்றும் கட்டணச் சுருக்கத்தைப் பார்க்க Wallet-ஐத் திறக்கவும்.",
      te: "మీ సంపాదన మరియు పేఅవుట్ చూడటానికి Wallet తెరవండి.",
      mr: "तुमची कमाई आणि पेआउट पाहण्यासाठी Wallet उघडा.",
      bn: "আপনার আয় এবং পেআউট দেখতে Wallet খুলুন।",
      gu: "તમારી કમાણી અને પેઆઉટ જોવા Wallet ખોલો.",
      ml: "നിങ്ങളുടെ വരുമാനവും പേഔട്ടും കാണാൻ Wallet തുറക്കുക.",
      pa: "ਆਪਣੀ ਕਮਾਈ ਅਤੇ ਭੁਗਤਾਨ ਵੇਖਣ ਲਈ Wallet ਖੋਲ੍ਹੋ।",
      ur: "اپنی کمائی اور ادائیگی دیکھنے کے لیے Wallet کھولیں۔",
    },
  },
];

const ADMIN_FAQ: FaqIntent[] = [
  {
    id: "view_orders",
    keywords: ["view orders", "see orders", "all orders"],
    route: "/admin/orders",
    actionLabel: {
      en: "Orders", hi: "ऑर्डर", hinglish: "Orders",
      kn: "ಆರ್ಡರ್‌ಗಳು", ta: "ஆர்டர்கள்", te: "ఆర్డర్లు",
      mr: "ऑर्डर्स", bn: "অর্ডার", gu: "ઓર્ડર", ml: "ഓർഡറുകൾ",
      pa: "ਆਰਡਰ", ur: "آرڈرز",
    },
    answer: {
      en: "Open Orders to see every order across the platform.",
      hi: "पूरे प्लेटफॉर्म के सभी ऑर्डर देखने के लिए Orders खोलें।",
      hinglish: "Poore platform ke sabhi orders dekhne ke liye Orders kholo.",
      kn: "ಇಡೀ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನ ಎಲ್ಲಾ ಆರ್ಡರ್ ನೋಡಲು Orders ತೆರೆಯಿರಿ.",
      ta: "தளம் முழுவதும் உள்ள அனைத்து ஆர்டர்களையும் பார்க்க Orders-ஐத் திறக்கவும்.",
      te: "ప్లాట్‌ఫారమ్ మొత్తంలో అన్ని ఆర్డర్లు చూడటానికి Orders తెరవండి.",
      mr: "संपूर्ण प्लॅटफॉर्मवरील सर्व ऑर्डर्स पाहण्यासाठी Orders उघडा.",
      bn: "সম্পূর্ণ প্ল্যাটফর্মের সব অর্ডার দেখতে Orders খুলুন।",
      gu: "સમગ્ર પ્લેટફોર્મના તમામ ઓર્ડર જોવા Orders ખોલો.",
      ml: "പ്ലാറ്റ്ഫോമിലെ എല്ലാ ഓർഡറുകളും കാണാൻ Orders തുറക്കുക.",
      pa: "ਪੂਰੇ ਪਲੇਟਫਾਰਮ ਦੇ ਸਾਰੇ ਆਰਡਰ ਵੇਖਣ ਲਈ Orders ਖੋਲ੍ਹੋ।",
      ur: "پورے پلیٹ فارم کے تمام آرڈرز دیکھنے کے لیے Orders کھولیں۔",
    },
  },
  {
    id: "manage_restaurants",
    keywords: ["manage restaurants", "approve restaurant", "suspend restaurant"],
    route: "/admin/restaurants",
    actionLabel: {
      en: "Restaurants", hi: "रेस्टोरेंट", hinglish: "Restaurants",
      kn: "ರೆಸ್ಟೋರೆಂಟ್‌ಗಳು", ta: "உணவகங்கள்", te: "రెస్టారెంట్లు",
      mr: "रेस्टॉरंट्स", bn: "রেস্তোরাঁ", gu: "રેસ્ટોરન્ટ", ml: "റെസ്റ്റോറന്റുകൾ",
      pa: "ਰੈਸਟੋਰੈਂਟ", ur: "ریسٹورنٹس",
    },
    answer: {
      en: "Open Restaurants to approve, suspend, or review restaurant partners.",
      hi: "रेस्टोरेंट पार्टनर्स को स्वीकृत/निलंबित करने के लिए Restaurants खोलें।",
      hinglish: "Restaurant partners approve/suspend karne ke liye Restaurants kholo.",
      kn: "ರೆಸ್ಟೋರೆಂಟ್ ಪಾಲುದಾರರನ್ನು ಅನುಮೋದಿಸಲು/ಅಮಾನತುಗೊಳಿಸಲು Restaurants ತೆರೆಯಿರಿ.",
      ta: "உணவக பங்குதாரர்களை அங்கீகரிக்க/நிறுத்த Restaurants-ஐத் திறக்கவும்.",
      te: "రెస్టారెంట్ భాగస్వాములను ఆమోదించడానికి/సస్పెండ్ చేయడానికి Restaurants తెరవండి.",
      mr: "रेस्टॉरंट पार्टनर्स मंजूर/निलंबित करण्यासाठी Restaurants उघडा.",
      bn: "রেস্তোরাঁ পার্টনার অনুমোদন/স্থগিত করতে Restaurants খুলুন।",
      gu: "રેસ્ટોરન્ટ પાર્ટનર્સ મંજૂર/સસ્પેન્ડ કરવા Restaurants ખોલો.",
      ml: "റെസ്റ്റോറന്റ് പങ്കാളികളെ അംഗീകരിക്കാൻ/സസ്പെൻഡ് ചെയ്യാൻ Restaurants തുറക്കുക.",
      pa: "ਰੈਸਟੋਰੈਂਟ ਪਾਰਟਨਰ ਮਨਜ਼ੂਰ/ਮੁਅੱਤਲ ਕਰਨ ਲਈ Restaurants ਖੋਲ੍ਹੋ।",
      ur: "ریسٹورنٹ پارٹنرز کو منظور/معطل کرنے کے لیے Restaurants کھولیں۔",
    },
  },
  {
    id: "check_users",
    keywords: ["check users", "view users", "customers", "user list"],
    route: "/admin/customers",
    actionLabel: {
      en: "Users", hi: "यूज़र्स", hinglish: "Users",
      kn: "ಬಳಕೆದಾರರು", ta: "பயனர்கள்", te: "వినియోగదారులు",
      mr: "युजर्स", bn: "ব্যবহারকারী", gu: "વપરાશકર્તાઓ", ml: "ഉപയോക്താക്കൾ",
      pa: "ਯੂਜ਼ਰ", ur: "صارفین",
    },
    answer: {
      en: "Open Customers to view customer accounts, or Fleet for drivers.",
      hi: "ग्राहक देखने के लिए Customers, ड्राइवरों के लिए Fleet खोलें।",
      hinglish: "Customers dekhne ke liye Customers, drivers ke liye Fleet kholo.",
      kn: "ಗ್ರಾಹಕರಿಗಾಗಿ Customers, ಚಾಲಕರಿಗಾಗಿ Fleet ತೆರೆಯಿರಿ.",
      ta: "வாடிக்கையாளர்களுக்கு Customers, ஓட்டுநர்களுக்கு Fleet-ஐத் திறக்கவும்.",
      te: "కస్టమర్ల కోసం Customers, డ్రైవర్ల కోసం Fleet తెరవండి.",
      mr: "ग्राहकांसाठी Customers, ड्रायव्हर्ससाठी Fleet उघडा.",
      bn: "গ্রাহকদের জন্য Customers, ড্রাইভারদের জন্য Fleet খুলুন।",
      gu: "ગ્રાહકો માટે Customers, ડ્રાઈવરો માટે Fleet ખોલો.",
      ml: "ഉപഭോക്താക്കൾക്ക് Customers, ഡ്രൈവർമാർക്ക് Fleet തുറക്കുക.",
      pa: "ਗਾਹਕਾਂ ਲਈ Customers, ਡਰਾਈਵਰਾਂ ਲਈ Fleet ਖੋਲ੍ਹੋ।",
      ur: "کسٹمرز کے لیے Customers، ڈرائیورز کے لیے Fleet کھولیں۔",
    },
  },
  {
    id: "platform_revenue",
    keywords: ["platform revenue", "revenue", "earnings report"],
    route: "/admin/finance",
    actionLabel: {
      en: "Dashboard", hi: "डैशबोर्ड", hinglish: "Dashboard",
      kn: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", ta: "டாஷ்போர்டு", te: "డాష్‌బోర్డ్",
      mr: "डॅशबोर्ड", bn: "ড্যাশবোর্ড", gu: "ડેશબોર્ડ", ml: "ഡാഷ്ബോർഡ്",
      pa: "ਡੈਸ਼ਬੋਰਡ", ur: "ڈیش بورڈ",
    },
    answer: {
      en: "Open Finance to see platform revenue and settlement figures.",
      hi: "प्लेटफॉर्म आय और सेटलमेंट देखने के लिए Finance खोलें।",
      hinglish: "Platform revenue aur settlement dekhne ke liye Finance kholo.",
      kn: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಆದಾಯ ಮತ್ತು ಇತ್ಯರ್ಥ ನೋಡಲು Finance ತೆರೆಯಿರಿ.",
      ta: "தள வருவாய் மற்றும் தீர்வுத் தொகைகளைப் பார்க்க Finance-ஐத் திறக்கவும்.",
      te: "ప్లాట్‌ఫారమ్ ఆదాయం మరియు సెటిల్‌మెంట్ చూడటానికి Finance తెరవండి.",
      mr: "प्लॅटफॉर्म महसूल आणि सेटलमेंट पाहण्यासाठी Finance उघडा.",
      bn: "প্ল্যাটফর্ম আয় এবং সেটলমেন্ট দেখতে Finance খুলুন।",
      gu: "પ્લેટફોર્મ આવક અને સેટલમેન્ટ જોવા Finance ખોલો.",
      ml: "പ്ലാറ്റ്ഫോം വരുമാനവും സെറ്റിൽമെന്റും കാണാൻ Finance തുറക്കുക.",
      pa: "ਪਲੇਟਫਾਰਮ ਆਮਦਨ ਅਤੇ ਸੈਟਲਮੈਂਟ ਵੇਖਣ ਲਈ Finance ਖੋਲ੍ਹੋ।",
      ur: "پلیٹ فارم کی آمدنی اور سیٹلمنٹ دیکھنے کے لیے Finance کھولیں۔",
    },
  },
];

export const FAQ_BY_ROLE: Record<UserRole, FaqIntent[]> = {
  [UserRole.CUSTOMER]: CUSTOMER_FAQ,
  [UserRole.RESTAURANT_OWNER]: RESTAURANT_FAQ,
  [UserRole.DELIVERY_PARTNER]: DRIVER_FAQ,
  [UserRole.ADMIN]: ADMIN_FAQ,
};

export const GREETING: L = {
  en: "Hi! How can I help you today?",
  hi: "नमस्ते! मैं आपकी कैसे मदद कर सकता हूँ?",
  hinglish: "Hi! Aapki kaise madad kar sakta hoon?",
  kn: "ನಮಸ್ಕಾರ! ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  ta: "வணக்கம்! நான் உங்களுக்கு எப்படி உதவலாம்?",
  te: "నమస్తే! నేను మీకు ఎలా సహాయం చేయగలను?",
  mr: "नमस्कार! मी तुम्हाला कशी मदत करू शकतो?",
  bn: "হ্যালো! আমি কীভাবে আপনাকে সাহায্য করতে পারি?",
  gu: "નમસ્તે! હું તમને કેવી રીતે મદદ કરી શકું?",
  ml: "നമസ്കാരം! ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കാം?",
  pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
  ur: "السلام علیکم! میں آپ کی کیسے مدد کر سکتا ہوں؟",
};

export const FALLBACK_INTRO: L = {
  en: "I couldn't find an exact match — here's what I can help with:",
  hi: "मुझे सटीक उत्तर नहीं मिला — यहाँ मैं इनमें मदद कर सकता हूँ:",
  hinglish: "Exact jawab nahi mila — main inme madad kar sakta hoon:",
  kn: "ನಿಖರ ಉತ್ತರ ಸಿಗಲಿಲ್ಲ — ನಾನು ಇವುಗಳಲ್ಲಿ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ:",
  ta: "சரியான பதில் கிடைக்கவில்லை — இவற்றில் உதவ முடியும்:",
  te: "సరైన సమాధానం దొరకలేదు — వీటిలో సహాయం చేయగలను:",
  mr: "नेमके उत्तर मिळाले नाही — मी यामध्ये मदत करू शकतो:",
  bn: "সঠিক উত্তর পাইনি — এগুলোতে সাহায্য করতে পারি:",
  gu: "ચોક્કસ જવાબ ન મળ્યો — હું આમાં મદદ કરી શકું:",
  ml: "കൃത്യമായ ഉത്തരം കിട്ടിയില്ല — ഇവയിൽ സഹായിക്കാം:",
  pa: "ਸਹੀ ਜਵਾਬ ਨਹੀਂ ਮਿਲਿਆ — ਮੈਂ ਇਹਨਾਂ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ:",
  ur: "صحیح جواب نہیں ملا — میں ان میں مدد کر سکتا ہوں:",
};
